name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: dependencies
      run: sudo apt-get install coreutils build-essential gcc-7 g++-7 gfortran-7 libgsl-dev libgslcblas0 qt5-default qtcreator dvipng -y
    - name: configure
      run: source setup.sh .install
    - name: make
      run: |
        source marty_env.sh
        make
    - name: install
      run: make install
    - name: download-tests
      run: git clone https://github.com/docbrown1955/test-suite.git
    - name: run-tests
      run: |
        source marty_env.sh
        cd test-suite
        ./launch_tests.sh
  
  build-and-test-mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: dependencies
      run: |
        brew install coreutils gcc@7 gsl qt5
        brew install --cask qt-creator
    - name: configure
      run: source setup.sh .install
    - name: make
      run: |
        source marty_env.sh
        make
    - name: install
      run: make install
    - name: download-tests
      run: git clone https://github.com/docbrown1955/test-suite.git
    - name: run-tests
      run: |
        source marty_env.sh
        cd test-suite
        ./launch_tests.sh
