name: C/C++ CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    types:
      - ready_for_review
      - review_requested

jobs:
  build-and-test-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: dependencies
      run: sudo apt-get install coreutils build-essential gcc-7 g++-7 gfortran-7 libgsl-dev libgslcblas0 qt5-default dvipng -y
    - name: configure
      run: |
        mkdir build
        cd build
        cmake ..
    - name: make
      run: |
        cd build
        make
    - name: install
      run: |
        cd build
        sudo make install
    - name: download-tests
      run: git clone https://github.com/docbrown1955/test-suite.git
    - name: run-tests
      run: |
        source marty_env.sh
        cd test-suite
        ./launch_tests.sh
