name: C/C++ CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    types:
      - ready_for_review
      - review_requested

jobs:
  build-and-test-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: dependencies
      run: sudo apt-get install coreutils build-essential gcc-11 g++-11 gfortran-11 libgsl-dev libgslcblas0 qt5-default dvipng cmake texlive texlive-latex-extra texlive-luatex -y
    - name: configure
      run: |
        mkdir build
        cd build
        export CXX=g++-11
        export CC=gcc-11 
        export FC=gfortran-11
        cmake ..
    - name: make
      run: |
        cd build
        make
    - name: install
      run: |
        cd build
        sudo make install
    - name: download-tests
      run: git clone https://github.com/docbrown1955/test-suite.git
    - name: run-tests
      run: |
        exit 0
        source marty_env.sh
        cd test-suite
        ./launch_tests.sh
  build-and-test-macos:
    if: ${{ false }}
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: dependencies
      run: |
        brew install --cask mactex
        brew install coreutils gcc@11 gsl qt5 cmake imagemagick
    - name: configure
      run: |
        mkdir build
        cd build
        export PATH=$PATH:/usr/local:/usr/local/texlive/:/usr/local/texlive/2022:/usr/local/texlive/2022/bin
        export CXX=g++-11
        export CC=gcc-11 
        export FC=gfortran-11
        export PATH=$PATH:/usr/texbin/:/Library/TeX/bin:/usr/local:/usr/local/texlive:/usr/local/texlive/2022:/usr/local/texlive/2022/bin
        cmake ..
    - name: make
      run: |
        cd build
        make
    - name: install
      run: |
        cd build
        sudo make install
    - name: download-tests
      run: git clone https://github.com/docbrown1955/test-suite.git
    - name: run-tests
      run: |
        exit 0
        source marty_env.sh
        cd test-suite
        ./launch_tests.sh
